import type { NextPage } from "next";
import Head from "next/head";
import styles from "../../styles/Home.module.css"; // change
import { useRouter } from 'next/router'

const User: NextPage = () => {
    const router = useRouter();
    const { id } = router.query;
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">users/{id}!</a>
        </h1>
      </main>

    </div>
  );
};

export default User;
