import type { NextPage } from "next";
import Head from "next/head";
import PageWrapper from "../../components/Layout/PageWrapper";
import styles from "../../styles/Home.module.css"; // change

const Users: NextPage = () => {
  return (
    <>
      {/* <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}
      <PageWrapper>
        <main className={styles.main}>
          <h1 className={styles.title}>
            Welcome to <a href="https://nextjs.org">Users!</a>
          </h1>
        </main>
      </PageWrapper>
    </>
  );
};

export default Users;
