# Close a funding round, compute quadratic funding and apply grant match

name: Close Funding Round

# Run Manually
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Contract address'
        # Default value if no value is explicitly provided
        default: ''
        # Input has to be provided for the workflow to run
        required: true
        
      matchpool_address:
        description: 'Match pool'
        default: ''
        required: true
        

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Send greeting
      run: echo "Computing funding for contract ${{ github.event.inputs.name }} from pool ${{ github.event.inputs.matchpool_address"
